// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type ContactUsDocumentDataSlicesSlice =
  | FaqSlice
  | ContactInformationSlice
  | ContactFormSlice;

/**
 * Content for Contact Us documents
 */
interface ContactUsDocumentData {
  /**
   * Slice Zone field in *Contact Us*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_us.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ContactUsDocumentDataSlicesSlice> /**
   * Meta Description field in *Contact Us*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: contact_us.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Contact Us*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_us.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Contact Us*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: contact_us.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Contact Us document from Prismic
 *
 * - **API ID**: `contact_us`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ContactUsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<ContactUsDocumentData>,
    "contact_us",
    Lang
  >;

type CourseDocumentDataSlicesSlice =
  | ContactInformationSlice
  | ContactFormSlice
  | LecturersSlice
  | ImportantDatesSlice
  | MainTopicsSlice
  | ProgrammeStructureSlice
  | CourseContactPersonSlice
  | ProcessSlice
  | TextAndImageSlice
  | SmallGallerySlice
  | FaqSlice
  | InfoSlice
  | SmallHeroSlice
  | FeaturesSlice
  | HeroSlice;

/**
 * Content for Course documents
 */
interface CourseDocumentData {
  /**
   * Course Name field in *Course*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: course.course_name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  course_name: prismic.KeyTextField;

  /**
   * Cover Image field in *Course*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: course.cover_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  cover_image: prismic.ImageField<never>;

  /**
   * Slice Zone field in *Course*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: course.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<CourseDocumentDataSlicesSlice> /**
   * Meta Description field in *Course*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: course.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Course*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: course.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Course*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: course.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Course document from Prismic
 *
 * - **API ID**: `course`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CourseDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<CourseDocumentData>, "course", Lang>;

type CoursesDocumentDataSlicesSlice = SmallHeroSlice;

/**
 * Content for Courses documents
 */
interface CoursesDocumentData {
  /**
   * Slice Zone field in *Courses*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: courses.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<CoursesDocumentDataSlicesSlice> /**
   * Meta Description field in *Courses*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: courses.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Courses*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: courses.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Courses*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: courses.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Courses document from Prismic
 *
 * - **API ID**: `courses`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CoursesDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<CoursesDocumentData>,
    "courses",
    Lang
  >;

type HomepageDocumentDataSlicesSlice =
  | SmallHeroSlice
  | MainTopicsSlice
  | ProcessSlice
  | ProgrammeStructureSlice
  | LecturersSlice
  | ImportantDatesSlice
  | FaqSlice
  | ContactInformationSlice
  | CourseContactPersonSlice
  | ContactFormSlice
  | SmallGallerySlice
  | FeaturesSlice
  | InfoSlice
  | TextAndImageSlice
  | HeroSlice;

/**
 * Content for Homepage documents
 */
interface HomepageDocumentData {
  /**
   * Slice Zone field in *Homepage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomepageDocumentDataSlicesSlice> /**
   * Meta Description field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: homepage.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Homepage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: homepage.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomepageDocumentData>,
    "homepage",
    Lang
  >;

type HowToApplyDocumentDataSlicesSlice =
  | ProgrammeStructureSlice
  | ImportantDatesSlice
  | LecturersSlice
  | MainTopicsSlice
  | CourseContactPersonSlice
  | ContactInformationSlice
  | ContactFormSlice
  | SmallGallerySlice
  | TextAndImageSlice
  | HeroSlice
  | InfoSlice
  | FeaturesSlice
  | FaqSlice
  | ProcessSlice
  | SmallHeroSlice;

/**
 * Content for How To Apply documents
 */
interface HowToApplyDocumentData {
  /**
   * Slice Zone field in *How To Apply*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: how_to_apply.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HowToApplyDocumentDataSlicesSlice> /**
   * Meta Description field in *How To Apply*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: how_to_apply.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *How To Apply*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: how_to_apply.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *How To Apply*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: how_to_apply.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * How To Apply document from Prismic
 *
 * - **API ID**: `how_to_apply`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HowToApplyDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HowToApplyDocumentData>,
    "how_to_apply",
    Lang
  >;

type NavigationDocumentDataSlicesSlice = NavigationItemSlice;

/**
 * Content for Navigation documents
 */
interface NavigationDocumentData {
  /**
   * Button Text field in *Navigation*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.button_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_text: prismic.KeyTextField;

  /**
   * Button Link field in *Navigation*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.button_link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_link: prismic.LinkField;

  /**
   * Slice Zone field in *Navigation*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<NavigationDocumentDataSlicesSlice>;
}

/**
 * Navigation document from Prismic
 *
 * - **API ID**: `navigation`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NavigationDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<NavigationDocumentData>,
    "navigation",
    Lang
  >;

type UniversityOfSplitDocumentDataSlicesSlice =
  | SmallHeroSlice
  | SmallGallerySlice
  | ProgrammeStructureSlice
  | MainTopicsSlice
  | ProcessSlice
  | LecturersSlice
  | InfoSlice
  | ImportantDatesSlice
  | FaqSlice
  | FeaturesSlice
  | HeroSlice
  | CourseContactPersonSlice
  | ContactInformationSlice
  | ContactFormSlice
  | TextAndImageSlice;

/**
 * Content for University of Split documents
 */
interface UniversityOfSplitDocumentData {
  /**
   * Slice Zone field in *University of Split*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: university_of_split.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<UniversityOfSplitDocumentDataSlicesSlice> /**
   * Meta Description field in *University of Split*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: university_of_split.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *University of Split*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: university_of_split.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *University of Split*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: university_of_split.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * University of Split document from Prismic
 *
 * - **API ID**: `university_of_split`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type UniversityOfSplitDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<UniversityOfSplitDocumentData>,
    "university_of_split",
    Lang
  >;

export type AllDocumentTypes =
  | ContactUsDocument
  | CourseDocument
  | CoursesDocument
  | HomepageDocument
  | HowToApplyDocument
  | NavigationDocument
  | UniversityOfSplitDocument;

/**
 * Primary content in *ContactForm → Primary*
 */
export interface ContactFormSliceDefaultPrimary {
  /**
   * Heading field in *ContactForm → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_form.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Overtitle field in *ContactForm → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_form.primary.overtitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  overtitle: prismic.KeyTextField;

  /**
   * Content field in *ContactForm → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_form.primary.content
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  content: prismic.KeyTextField;

  /**
   * Button Text field in *ContactForm → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_form.primary.button_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_text: prismic.KeyTextField;
}

/**
 * Default variation for ContactForm Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactFormSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ContactFormSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ContactForm*
 */
type ContactFormSliceVariation = ContactFormSliceDefault;

/**
 * ContactForm Shared Slice
 *
 * - **API ID**: `contact_form`
 * - **Description**: ContactForm
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactFormSlice = prismic.SharedSlice<
  "contact_form",
  ContactFormSliceVariation
>;

/**
 * Primary content in *ContactInformation → Primary*
 */
export interface ContactInformationSliceDefaultPrimary {
  /**
   * Heading field in *ContactInformation → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_information.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Content field in *ContactInformation → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_information.primary.content
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  content: prismic.KeyTextField;

  /**
   * Address field in *ContactInformation → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_information.primary.address
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  address: prismic.KeyTextField;

  /**
   * Email field in *ContactInformation → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_information.primary.email
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  email: prismic.KeyTextField;

  /**
   * Phone field in *ContactInformation → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_information.primary.phone
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  phone: prismic.KeyTextField;

  /**
   * Location Embed field in *ContactInformation → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_information.primary.location_embed
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  location_embed: prismic.KeyTextField;
}

/**
 * Default variation for ContactInformation Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactInformationSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ContactInformationSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ContactInformation*
 */
type ContactInformationSliceVariation = ContactInformationSliceDefault;

/**
 * ContactInformation Shared Slice
 *
 * - **API ID**: `contact_information`
 * - **Description**: ContactInformation
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactInformationSlice = prismic.SharedSlice<
  "contact_information",
  ContactInformationSliceVariation
>;

/**
 * Primary content in *CourseContactPerson → Primary*
 */
export interface CourseContactPersonSliceDefaultPrimary {
  /**
   * Name field in *CourseContactPerson → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: course_contact_person.primary.name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * Phone field in *CourseContactPerson → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: course_contact_person.primary.phone
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  phone: prismic.KeyTextField;

  /**
   * Email field in *CourseContactPerson → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: course_contact_person.primary.email
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  email: prismic.KeyTextField;
}

/**
 * Default variation for CourseContactPerson Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CourseContactPersonSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CourseContactPersonSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *CourseContactPerson*
 */
type CourseContactPersonSliceVariation = CourseContactPersonSliceDefault;

/**
 * CourseContactPerson Shared Slice
 *
 * - **API ID**: `course_contact_person`
 * - **Description**: CourseContactPerson
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CourseContactPersonSlice = prismic.SharedSlice<
  "course_contact_person",
  CourseContactPersonSliceVariation
>;

/**
 * Primary content in *Faq → Primary*
 */
export interface FaqSliceDefaultPrimary {
  /**
   * Heading field in *Faq → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Content field in *Faq → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.primary.content
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  content: prismic.KeyTextField;
}

/**
 * Primary content in *Faq → Items*
 */
export interface FaqSliceDefaultItem {
  /**
   * Question field in *Faq → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.items[].question
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  question: prismic.KeyTextField;

  /**
   * Answer field in *Faq → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.items[].answer
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  answer: prismic.KeyTextField;
}

/**
 * Default variation for Faq Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FaqSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FaqSliceDefaultPrimary>,
  Simplify<FaqSliceDefaultItem>
>;

/**
 * Slice variation for *Faq*
 */
type FaqSliceVariation = FaqSliceDefault;

/**
 * Faq Shared Slice
 *
 * - **API ID**: `faq`
 * - **Description**: Faq
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FaqSlice = prismic.SharedSlice<"faq", FaqSliceVariation>;

/**
 * Primary content in *Features → Primary*
 */
export interface FeaturesSliceDefaultPrimary {
  /**
   * Heading field in *Features → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: features.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Content field in *Features → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: features.primary.content
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  content: prismic.KeyTextField;
}

/**
 * Primary content in *Features → Items*
 */
export interface FeaturesSliceDefaultItem {
  /**
   * Feature field in *Features → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: features.items[].feature
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  feature: prismic.KeyTextField;
}

/**
 * Default variation for Features Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FeaturesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FeaturesSliceDefaultPrimary>,
  Simplify<FeaturesSliceDefaultItem>
>;

/**
 * Slice variation for *Features*
 */
type FeaturesSliceVariation = FeaturesSliceDefault;

/**
 * Features Shared Slice
 *
 * - **API ID**: `features`
 * - **Description**: Features
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FeaturesSlice = prismic.SharedSlice<
  "features",
  FeaturesSliceVariation
>;

/**
 * Primary content in *Hero → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * Heading field in *Hero → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Overtitle field in *Hero → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.overtitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  overtitle: prismic.KeyTextField;

  /**
   * Subheading field in *Hero → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.subheading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subheading: prismic.KeyTextField;

  /**
   * Image field in *Hero → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Button Text field in *Hero → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.button_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_text: prismic.KeyTextField;

  /**
   * Button Link field in *Hero → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.button_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_link: prismic.LinkField;

  /**
   * Video Embed Link field in *Hero → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.video_embed_link
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  video_embed_link: prismic.KeyTextField;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Primary content in *ImportantDates → Primary*
 */
export interface ImportantDatesSliceDefaultPrimary {
  /**
   * Heading field in *ImportantDates → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: important_dates.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Course Dates field in *ImportantDates → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: important_dates.primary.course_dates
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  course_dates: prismic.KeyTextField;

  /**
   * Deadline for Application field in *ImportantDates → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: important_dates.primary.deadline_for_application
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  deadline_for_application: prismic.KeyTextField;

  /**
   * Confirmation of the course field in *ImportantDates → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: important_dates.primary.confirmation_of_the_course
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  confirmation_of_the_course: prismic.KeyTextField;

  /**
   * Payment due by field in *ImportantDates → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: important_dates.primary.payment_due_by
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  payment_due_by: prismic.KeyTextField;
}

/**
 * Default variation for ImportantDates Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImportantDatesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ImportantDatesSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ImportantDates*
 */
type ImportantDatesSliceVariation = ImportantDatesSliceDefault;

/**
 * ImportantDates Shared Slice
 *
 * - **API ID**: `important_dates`
 * - **Description**: ImportantDates
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImportantDatesSlice = prismic.SharedSlice<
  "important_dates",
  ImportantDatesSliceVariation
>;

/**
 * Primary content in *Info → Primary*
 */
export interface InfoSliceDefaultPrimary {
  /**
   * Heading field in *Info → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: info.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Overtitle field in *Info → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: info.primary.overtitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  overtitle: prismic.KeyTextField;

  /**
   * Content field in *Info → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: info.primary.content
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  content: prismic.KeyTextField;

  /**
   * Link Text field in *Info → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: info.primary.link_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link_text: prismic.KeyTextField;

  /**
   * Link field in *Info → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: info.primary.link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;

  /**
   * Box1 Heading field in *Info → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: info.primary.box1_heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  box1_heading: prismic.KeyTextField;

  /**
   * Box1 Overtitle field in *Info → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: info.primary.box1_overtitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  box1_overtitle: prismic.KeyTextField;

  /**
   * Box1 Subtitle field in *Info → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: info.primary.box1_subtitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  box1_subtitle: prismic.KeyTextField;

  /**
   * Box1 Content field in *Info → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: info.primary.box1_content
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  box1_content: prismic.KeyTextField;

  /**
   * Box1 Button Text field in *Info → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: info.primary.box1_button_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  box1_button_text: prismic.KeyTextField;

  /**
   * Box1 Button Link field in *Info → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: info.primary.box1_button_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  box1_button_link: prismic.LinkField;

  /**
   * Box2 Heading field in *Info → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: info.primary.box2_heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  box2_heading: prismic.KeyTextField;

  /**
   * Box2 Overtitle field in *Info → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: info.primary.box2_overtitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  box2_overtitle: prismic.KeyTextField;

  /**
   * Box2 Subtitle field in *Info → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: info.primary.box2_subtitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  box2_subtitle: prismic.KeyTextField;

  /**
   * Box2 Content field in *Info → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: info.primary.box2_content
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  box2_content: prismic.KeyTextField;

  /**
   * Box2 Button Text field in *Info → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: info.primary.box2_button_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  box2_button_text: prismic.KeyTextField;

  /**
   * Box2 Button Link field in *Info → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: info.primary.box2_button_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  box2_button_link: prismic.LinkField;
}

/**
 * Default variation for Info Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type InfoSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<InfoSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Info*
 */
type InfoSliceVariation = InfoSliceDefault;

/**
 * Info Shared Slice
 *
 * - **API ID**: `info`
 * - **Description**: Info
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type InfoSlice = prismic.SharedSlice<"info", InfoSliceVariation>;

/**
 * Primary content in *Lecturers → Primary*
 */
export interface LecturersSliceDefaultPrimary {
  /**
   * Heading field in *Lecturers → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: lecturers.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Content field in *Lecturers → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: lecturers.primary.content
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  content: prismic.KeyTextField;
}

/**
 * Primary content in *Lecturers → Items*
 */
export interface LecturersSliceDefaultItem {
  /**
   * Name field in *Lecturers → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: lecturers.items[].name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * Position field in *Lecturers → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: lecturers.items[].position
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  position: prismic.KeyTextField;

  /**
   * Image field in *Lecturers → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: lecturers.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for Lecturers Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LecturersSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<LecturersSliceDefaultPrimary>,
  Simplify<LecturersSliceDefaultItem>
>;

/**
 * Slice variation for *Lecturers*
 */
type LecturersSliceVariation = LecturersSliceDefault;

/**
 * Lecturers Shared Slice
 *
 * - **API ID**: `lecturers`
 * - **Description**: Lecturers
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LecturersSlice = prismic.SharedSlice<
  "lecturers",
  LecturersSliceVariation
>;

/**
 * Primary content in *MainTopics → Primary*
 */
export interface MainTopicsSliceDefaultPrimary {
  /**
   * Heading field in *MainTopics → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: main_topics.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;
}

/**
 * Primary content in *MainTopics → Items*
 */
export interface MainTopicsSliceDefaultItem {
  /**
   * List Item field in *MainTopics → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: main_topics.items[].list_item
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  list_item: prismic.KeyTextField;
}

/**
 * Default variation for MainTopics Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MainTopicsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<MainTopicsSliceDefaultPrimary>,
  Simplify<MainTopicsSliceDefaultItem>
>;

/**
 * Slice variation for *MainTopics*
 */
type MainTopicsSliceVariation = MainTopicsSliceDefault;

/**
 * MainTopics Shared Slice
 *
 * - **API ID**: `main_topics`
 * - **Description**: MainTopics
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MainTopicsSlice = prismic.SharedSlice<
  "main_topics",
  MainTopicsSliceVariation
>;

/**
 * Primary content in *NavigationItem → Primary*
 */
export interface NavigationItemSliceDefaultPrimary {
  /**
   * Label field in *NavigationItem → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation_item.primary.label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;

  /**
   * Link field in *NavigationItem → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation_item.primary.link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Primary content in *NavigationItem → Items*
 */
export interface NavigationItemSliceDefaultItem {
  /**
   * Child Label field in *NavigationItem → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation_item.items[].child_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  child_label: prismic.KeyTextField;

  /**
   * Child Link field in *NavigationItem → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation_item.items[].child_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  child_link: prismic.LinkField;
}

/**
 * Default variation for NavigationItem Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NavigationItemSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<NavigationItemSliceDefaultPrimary>,
  Simplify<NavigationItemSliceDefaultItem>
>;

/**
 * Slice variation for *NavigationItem*
 */
type NavigationItemSliceVariation = NavigationItemSliceDefault;

/**
 * NavigationItem Shared Slice
 *
 * - **API ID**: `navigation_item`
 * - **Description**: NavigationItem
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NavigationItemSlice = prismic.SharedSlice<
  "navigation_item",
  NavigationItemSliceVariation
>;

/**
 * Primary content in *Process → Primary*
 */
export interface ProcessSliceDefaultPrimary {
  /**
   * Heading field in *Process → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: process.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Content field in *Process → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: process.primary.content
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  content: prismic.KeyTextField;
}

/**
 * Primary content in *Process → Items*
 */
export interface ProcessSliceDefaultItem {
  /**
   * Heading field in *Process → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: process.items[].heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Content field in *Process → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: process.items[].item_content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  item_content: prismic.RichTextField;
}

/**
 * Default variation for Process Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProcessSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ProcessSliceDefaultPrimary>,
  Simplify<ProcessSliceDefaultItem>
>;

/**
 * Slice variation for *Process*
 */
type ProcessSliceVariation = ProcessSliceDefault;

/**
 * Process Shared Slice
 *
 * - **API ID**: `process`
 * - **Description**: Process
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProcessSlice = prismic.SharedSlice<
  "process",
  ProcessSliceVariation
>;

/**
 * Primary content in *ProgrammeStructure → Primary*
 */
export interface ProgrammeStructureSliceDefaultPrimary {
  /**
   * Heading field in *ProgrammeStructure → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: programme_structure.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;
}

/**
 * Primary content in *ProgrammeStructure → Items*
 */
export interface ProgrammeStructureSliceDefaultItem {
  /**
   * List Item field in *ProgrammeStructure → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: programme_structure.items[].list_item
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  list_item: prismic.KeyTextField;
}

/**
 * Default variation for ProgrammeStructure Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProgrammeStructureSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ProgrammeStructureSliceDefaultPrimary>,
  Simplify<ProgrammeStructureSliceDefaultItem>
>;

/**
 * Slice variation for *ProgrammeStructure*
 */
type ProgrammeStructureSliceVariation = ProgrammeStructureSliceDefault;

/**
 * ProgrammeStructure Shared Slice
 *
 * - **API ID**: `programme_structure`
 * - **Description**: ProgrammeStructure
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProgrammeStructureSlice = prismic.SharedSlice<
  "programme_structure",
  ProgrammeStructureSliceVariation
>;

/**
 * Primary content in *SmallGallery → Primary*
 */
export interface SmallGallerySliceDefaultPrimary {
  /**
   * Heading field in *SmallGallery → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: small_gallery.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Overtitle field in *SmallGallery → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: small_gallery.primary.overtitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  overtitle: prismic.KeyTextField;

  /**
   * Content field in *SmallGallery → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: small_gallery.primary.content
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  content: prismic.KeyTextField;

  /**
   * Image 1 field in *SmallGallery → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: small_gallery.primary.image_1
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_1: prismic.ImageField<never>;

  /**
   * Image 2 field in *SmallGallery → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: small_gallery.primary.image_2
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_2: prismic.ImageField<never>;

  /**
   * Image 3 field in *SmallGallery → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: small_gallery.primary.image_3
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_3: prismic.ImageField<never>;

  /**
   * Image 4 field in *SmallGallery → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: small_gallery.primary.image_4
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_4: prismic.ImageField<never>;

  /**
   * Image 5 field in *SmallGallery → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: small_gallery.primary.image_5
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_5: prismic.ImageField<never>;

  /**
   * Image 6 field in *SmallGallery → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: small_gallery.primary.image_6
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_6: prismic.ImageField<never>;
}

/**
 * Default variation for SmallGallery Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SmallGallerySliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SmallGallerySliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *SmallGallery*
 */
type SmallGallerySliceVariation = SmallGallerySliceDefault;

/**
 * SmallGallery Shared Slice
 *
 * - **API ID**: `small_gallery`
 * - **Description**: SmallGallery
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SmallGallerySlice = prismic.SharedSlice<
  "small_gallery",
  SmallGallerySliceVariation
>;

/**
 * Primary content in *SmallHero → Primary*
 */
export interface SmallHeroSliceDefaultPrimary {
  /**
   * Heading field in *SmallHero → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: small_hero.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Overtitle field in *SmallHero → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: small_hero.primary.overtitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  overtitle: prismic.KeyTextField;

  /**
   * Content field in *SmallHero → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: small_hero.primary.content
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  content: prismic.KeyTextField;
}

/**
 * Default variation for SmallHero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SmallHeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SmallHeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *SmallHero*
 */
type SmallHeroSliceVariation = SmallHeroSliceDefault;

/**
 * SmallHero Shared Slice
 *
 * - **API ID**: `small_hero`
 * - **Description**: SmallHero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SmallHeroSlice = prismic.SharedSlice<
  "small_hero",
  SmallHeroSliceVariation
>;

/**
 * Primary content in *TextAndImage → Primary*
 */
export interface TextAndImageSliceDefaultPrimary {
  /**
   * Heading field in *TextAndImage → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_and_image.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Overtitle field in *TextAndImage → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_and_image.primary.overtitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  overtitle: prismic.KeyTextField;

  /**
   * Image field in *TextAndImage → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: text_and_image.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Content field in *TextAndImage → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_and_image.primary.content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;

  /**
   * Button Text field in *TextAndImage → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_and_image.primary.button_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_text: prismic.KeyTextField;

  /**
   * Button Link field in *TextAndImage → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: text_and_image.primary.button_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_link: prismic.LinkField;
}

/**
 * Default variation for TextAndImage Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextAndImageSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TextAndImageSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *TextAndImage → Primary*
 */
export interface TextAndImageSliceImageRightPrimary {
  /**
   * Heading field in *TextAndImage → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_and_image.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Overtitle field in *TextAndImage → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_and_image.primary.overtitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  overtitle: prismic.KeyTextField;

  /**
   * Image field in *TextAndImage → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: text_and_image.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Content field in *TextAndImage → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_and_image.primary.content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;

  /**
   * Button Text field in *TextAndImage → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_and_image.primary.button_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_text: prismic.KeyTextField;

  /**
   * Button Link field in *TextAndImage → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: text_and_image.primary.button_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_link: prismic.LinkField;
}

/**
 * Image Right variation for TextAndImage Slice
 *
 * - **API ID**: `imageRight`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextAndImageSliceImageRight = prismic.SharedSliceVariation<
  "imageRight",
  Simplify<TextAndImageSliceImageRightPrimary>,
  never
>;

/**
 * Slice variation for *TextAndImage*
 */
type TextAndImageSliceVariation =
  | TextAndImageSliceDefault
  | TextAndImageSliceImageRight;

/**
 * TextAndImage Shared Slice
 *
 * - **API ID**: `text_and_image`
 * - **Description**: TextAndImage
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextAndImageSlice = prismic.SharedSlice<
  "text_and_image",
  TextAndImageSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      ContactUsDocument,
      ContactUsDocumentData,
      ContactUsDocumentDataSlicesSlice,
      CourseDocument,
      CourseDocumentData,
      CourseDocumentDataSlicesSlice,
      CoursesDocument,
      CoursesDocumentData,
      CoursesDocumentDataSlicesSlice,
      HomepageDocument,
      HomepageDocumentData,
      HomepageDocumentDataSlicesSlice,
      HowToApplyDocument,
      HowToApplyDocumentData,
      HowToApplyDocumentDataSlicesSlice,
      NavigationDocument,
      NavigationDocumentData,
      NavigationDocumentDataSlicesSlice,
      UniversityOfSplitDocument,
      UniversityOfSplitDocumentData,
      UniversityOfSplitDocumentDataSlicesSlice,
      AllDocumentTypes,
      ContactFormSlice,
      ContactFormSliceDefaultPrimary,
      ContactFormSliceVariation,
      ContactFormSliceDefault,
      ContactInformationSlice,
      ContactInformationSliceDefaultPrimary,
      ContactInformationSliceVariation,
      ContactInformationSliceDefault,
      CourseContactPersonSlice,
      CourseContactPersonSliceDefaultPrimary,
      CourseContactPersonSliceVariation,
      CourseContactPersonSliceDefault,
      FaqSlice,
      FaqSliceDefaultPrimary,
      FaqSliceDefaultItem,
      FaqSliceVariation,
      FaqSliceDefault,
      FeaturesSlice,
      FeaturesSliceDefaultPrimary,
      FeaturesSliceDefaultItem,
      FeaturesSliceVariation,
      FeaturesSliceDefault,
      HeroSlice,
      HeroSliceDefaultPrimary,
      HeroSliceVariation,
      HeroSliceDefault,
      ImportantDatesSlice,
      ImportantDatesSliceDefaultPrimary,
      ImportantDatesSliceVariation,
      ImportantDatesSliceDefault,
      InfoSlice,
      InfoSliceDefaultPrimary,
      InfoSliceVariation,
      InfoSliceDefault,
      LecturersSlice,
      LecturersSliceDefaultPrimary,
      LecturersSliceDefaultItem,
      LecturersSliceVariation,
      LecturersSliceDefault,
      MainTopicsSlice,
      MainTopicsSliceDefaultPrimary,
      MainTopicsSliceDefaultItem,
      MainTopicsSliceVariation,
      MainTopicsSliceDefault,
      NavigationItemSlice,
      NavigationItemSliceDefaultPrimary,
      NavigationItemSliceDefaultItem,
      NavigationItemSliceVariation,
      NavigationItemSliceDefault,
      ProcessSlice,
      ProcessSliceDefaultPrimary,
      ProcessSliceDefaultItem,
      ProcessSliceVariation,
      ProcessSliceDefault,
      ProgrammeStructureSlice,
      ProgrammeStructureSliceDefaultPrimary,
      ProgrammeStructureSliceDefaultItem,
      ProgrammeStructureSliceVariation,
      ProgrammeStructureSliceDefault,
      SmallGallerySlice,
      SmallGallerySliceDefaultPrimary,
      SmallGallerySliceVariation,
      SmallGallerySliceDefault,
      SmallHeroSlice,
      SmallHeroSliceDefaultPrimary,
      SmallHeroSliceVariation,
      SmallHeroSliceDefault,
      TextAndImageSlice,
      TextAndImageSliceDefaultPrimary,
      TextAndImageSliceImageRightPrimary,
      TextAndImageSliceVariation,
      TextAndImageSliceDefault,
      TextAndImageSliceImageRight,
    };
  }
}
