// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  features: dynamic(() => import("./Features")),
  hero: dynamic(() => import("./Hero")),
  info: dynamic(() => import("./Info")),
  navigation_item: dynamic(() => import("./NavigationItem")),
  text_and_image: dynamic(() => import("./TextAndImage")),
};
